### ISSUE TITLE
[Bug] v3.1.0 regression from 3.0.4

### ISSUE THREAD

**Issue by Estheisia** [bestkolobok/vue3-jsoneditor#26]
In my Vue 3, Vite app (latest version), if i have the version 3.0.4 it seems fine but if I update to 3.1.0 then I got this error in the console at startup :

Uncaught TypeError: can't access property "exports", ks is undefined

<img width="499" height="146" alt="Image" src="https://github.com/user-attachments/assets/a692aba0-e6f9-44ab-883d-f2ecc6c4d75f" />

Which correspond to those lines in vendor generated file :
`var ks = { exports: {} }, Bo;
function C1() {
  if (Bo) return ks.exports;
  Bo = 1;
  var s = ks.exports = function(i, n, r) {`

- Maybe in tsconfig the change to `"moduleResolution": "bundler"` from the value "node" changed how it is build ?
- A lot of files in dist/ changed between version 🤔
- ESM droppped by error and only CommonJS is "exported" ?

**Comment by FrankMeissnerXledger** [comment]
Hello,

I'm having the same problem after updating to 3.1.0. I tried different browsers, no change.

**Comment by bestkolobok** [comment]
Hi,

Thank you for the report! The issue occurs due to the incompatibility of CommonJS modules (ajv and other vanilla-jsoneditor dependencies) with Vite during production build. I've updated the vite.config.js configuration by adding optimizeDeps with the corresponding dependencies. This should resolve the problem. Let me know if this issue still reproduces after updating to 3.1.1

**Comment by bestkolobok** [comment]
Sorry, I saw that after the release of the patch I forgot to push it to Github. I already pushed it, so you can see the changes to vite.config. I tested this build locally with different versions of Vit and the problem was gone. I will investigate further. Which version of Vite are you using, 6 or 7?

**Comment by Estheisia** [comment]
I retried, but still the same error, I tried to delete node-modules, change version, but starting v3.0.0 until 3.1.1 the error is appearing.

I use Vite 7
Here is some of my stack I thought might be relevant :
```
    "typescript": "5.9.3",
    "unplugin-vue-components": "30.0.0",

    "vite": "7.1.11",

    "vue": "^3.5.22",
    "vue-router": "^4.6.3",

    "vue3-ts-jsoneditor": "3.1.1",
```

I tried to downgrade vite to v6.4.1 but no change.
